In [1]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn.preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

from wrangle import

In [2]:
df = get_zillow_data()

In [3]:
df.head()

,Unnamed: 0,id,parcelid,bathroomcnt,bedroomcnt,fips,latitude,longitude,lotsizesquarefeet,propertycountylandusecode,...,transactiondate,propertylandusedesc,County,age,age_bin,acres,acres_bin,LA,Orange,Ventura
0,0,1727539,14297519,3.5,4.0,6059.0,33634931.0,-117869207.0,4506.0,122,...,2017-01-01,Single Family Residential,Orange County,19.0,0.133,0.103444,0.1,0,1,0
1,1,1387261,17052889,1.0,2.0,6111.0,34449266.0,-119281531.0,12647.0,1110,...,2017-01-01,Single Family Residential,Ventura County,50.0,0.333,0.290335,0.3,0,0,1
2,2,11677,14186244,2.0,3.0,6059.0,33886168.0,-117823170.0,8432.0,122,...,2017-01-01,Single Family Residential,Orange County,55.0,0.400,0.193572,0.2,0,1,0
3,3,2288172,12177905,3.0,4.0,6037.0,34245180.0,-118240722.0,13038.0,0101,...,2017-01-01,Single Family Residential,Los Angeles County,47.0,0.333,0.299311,0.3,1,0,0
4,4,781532,12095076,3.0,4.0,6037.0,34145202.0,-118179824.0,63000.0,0101,...,2017-01-01,Single Family Residential,Los Angeles County,67.0,0.466,1.446281,0.5,1,0,0

In [ ]:
df.head()

In [ ]:

# def train_validate_test_split(df):
#     '''
#     This function performs split on telco data, stratify churn.
#     Returns train, validate, and test dfs.
#     '''
#     train_validate, test = train_test_split(df, test_size=.2, 
#                                         random_state=123, stratify=df.fips)
#     train, validate = train_test_split(train_validate, test_size=.3, 
#                                    random_state=123,  stratify=train_validate.fips)

#     return train, validate, test

In [ ]:
# train, validate, test = train_validate_test_split(df)


# train.shape, validate.shape, test.shape